---

- name: install haproxy
  ansible.builtin.yum:
    name: haproxy
    state: present

- name: Configure etcd cluster
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: "/etc/haproxy/haproxy.cfg"
#  notify: Start etcd

- name: Start haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
    enabled: true
