---

# systemctl start etcd
- name: Start etcd
  ansible.builtin.service:
    name: etcd
    state: restarted
    enabled: true

# systemctl start patroni
- name: Start patroni
  ansible.builtin.service:
    name: patroni
    state: restarted
    enabled: true
 